name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Incrementar versión en README.md (Bump Version)
        shell: powershell
        run: |
          Write-Output "Incrementando versión en README.md..."
          (Get-Content README.md) -replace 'AppVersion-0', 'AppVersion-1' | Set-Content README.md

      - name: Validar despliegue en Producción
        shell: powershell
        run: |
          Write-Output "Despliegue ejecutado con éxito en la rama main."